name: Rust

on:
  push:
    branches: ["dev/setup-github-actions"]
  pull_request:
    branches: ["dev/setup-github-actions"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
