name: Rust

on:
  push:
    branches: ["dev/setup-github-actions"]
  pull_request:
    branches: ["dev/setup-github-actions"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cd backend && cargo build --verbose
      - name: Run tests
        run: cd backend && cargo test --verbose
