name: Sveltekit

on:
  push:
    branches: ["dev/setup-eslint"]
  pull_request:
    branches: ["dev/setup-eslint"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cd frontend && yarn build
      - name: Run Linter
        run: cd frontend && yarn lint
